paths:
  /api/products/:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Productos obtenidos correctamente
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      parameters:
        - name: body 
          in: body
          required: true
          schema:
            type: object
            properties:
              title: 
                type: string
              description: 
                type: string
              price: 
                type: number
              stock: 
                type: number
              category:
                type: string
              status:
                type: string
              code:
                type: string
              thumbnail:
                type: array   
      responses:
        '201':
          description: Producto creado correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
  /api/products/{id}:  
    get:
      summary: Obtener un Producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: ID del Producto a buscar
      responses:
        '200':
          description: Producto obtenido correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar un Producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: ID del Producto a actualizar
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              title: 
                type: string
              description: 
                type: string
              price: 
                type: number
              stock: 
                type: number
              category:
                type: string
              status:
                type: string
              code:
                type: string
              thumbnail:
                type: array 
      responses:
        '200':
          description: Producto actualizado correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar un Producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: ID del Producto a eliminar
      responses:
        '200':
          description: Producto Eliminado correctamente
          content: 
            application/json:
              schema: 
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor
components:
  schemas:
    Product: 
      type: object
      properties:
        _id: 
          type: 0bjectId
          description: ID autogenerado por MongoDb
        title: 
          type: String
          description: Nombre del producto
        description: 
          type: String
          description: Descripcion del Producto
        price: 
          type: Number
          description: Precio del Producto
        stock: 
          type: Number
          description: Stock del Producto
        category:
          type: String
          description: Categoria del Producto
        status:
          type: Boolean
          description: Estado de disponibilidad del Producto
        code:
          type: String
          description: Codigo del Producto
        thumbnail:
          type: Array
          description: Arreglo de imagenes del Producto      
      example:
        _id: ObjectId('31ewewx312312')
        title: Alfajor de Dulce de Leche
        description: Alfajor relleno de Dulce de Leche 
        price: 1000
        stock: 10
        category: Reposteria
        status: true
        code: ALF01
        thumbnail: ["imagen.jpg"]
      


    